### PR TITLE
Fix nil blob mode

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Bad blob entry keyword is used, so the blob mode is nil everywhere.

This PR fix that and add some tests about filemode (regular / executable / symlink).

The following Merge Request must be accepted to have spec working well: https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/1

Thanks.

### CODE REVIEW

**Comment by randx** [comment]
Please fix tests first

**Comment by DouweM** [comment]
@Soullivaneuh Looks like the fix got lost while fixing the tests :) Could you update this PR?

**Comment by Soullivaneuh** [comment]
@DouweM @randx Will do it soon.

**Comment by Soullivaneuh** [comment]
@randx As I said on my PR description:

> The following Merge Request must be accepted to have spec working well: https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/1

**Comment by Soullivaneuh** [comment]
Missing the change on blob class. It's fixed now.

But in any case, the related PR on gitlab-git-test must be merge to have all test green.

**Comment by randx** [comment]
@Soullivaneuh we merged https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/1 but tests still failing.

**Comment by Soullivaneuh** [comment]
@randx It's because:

```sh
$ ls -l support/mutable-repo.git/files/
total 20
drwxrwxr-x 2 sullivan sullivan 4096 mars  28 15:35 html
drwxrwxr-x 2 sullivan sullivan 4096 mars  28 15:35 images
drwxrwxr-x 2 sullivan sullivan 4096 mars  28 15:35 js
drwxrwxr-x 2 sullivan sullivan 4096 mars  28 15:35 markdown
drwxrwxr-x 2 sullivan sullivan 4096 mars  28 15:35 ruby
```

My [added files](https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/1/diffs) on PR are not present on test. Maybe a bad checkout, where can I change it?

**Comment by Soullivaneuh** [comment]
@randx Tests on `master` seems to have some random failed.

Can you please take a look and fix it if needed? I will rebase my PR after to fix mine.

Thanks.

**Comment by randx** [comment]
@Soullivaneuh I have green tests on latest master

**Comment by randx** [comment]
I see issue now. When I cloned gitlab_git to new directory tests failing. I guess its related to seomeone modifying test repo

**Comment by randx** [comment]
Lets wait for green tests in master then. I left a comment for @DouweM  https://gitlab.com/gitlab-org/gitlab-git-test/merge_requests/1#note_1030841

**Comment by Soullivaneuh** [comment]
@randx Please note that if an ran test multiples times, I don't have the same number of errors. Very weird.

**Comment by DouweM** [comment]
@Soullivaneuh Could you rebase and try again? With 12a8694cbc30cf43ecdadf8e2c2c7870d49cfbf6 the failing tests should have been fixed.

**Comment by Soullivaneuh** [comment]
Should be OK right now. :+1: 

cc @DouweM @randx

**Comment by DouweM** [comment]
Thank you @Soullivaneuh! Could you add a changelog item?

**Comment by Soullivaneuh** [comment]
Done. I created `7.1.4` section. I think you should push a new patch version because it's a fix with no BC break.

Tell me if you don't want that and want me to change the changelog again.

Regards.

**Comment by DouweM** [comment]
Makes sense to me. I'll release 7.1.4 in a minute. If you want it included into gitlab-ce, please create a separate MR for that there.

**Comment by DouweM** [comment]
@Soullivaneuh Looks like linguist expects mode to be a string, not an int. See the stack trace here: https://ci.gitlab.com/projects/1/builds/21808 and the referenced files in gitlab-linguist. Could you see what exactly linguist is looking for and fix that?

**Comment by Soullivaneuh** [comment]
@DouweM not sure to understand. It's a Gitlab CE test. What is the relation with this PR?

**Comment by DouweM** [comment]
@Soullivaneuh It's a test in CE, but it's testing functionaliy that uses gitlab_git:

```
/home/gitlab-runner/lib/ruby/gems/2.1.0/gems/gitlab-linguist-3.0.1/lib/linguist/language.rb:93:in `to_i': wrong number of arguments (1 for 0) (ActionView::Template::Error)
	from /home/gitlab-runner/lib/ruby/gems/2.1.0/gems/gitlab-linguist-3.0.1/lib/linguist/language.rb:93:in `detect'
	from /home/gitlab-runner/lib/ruby/gems/2.1.0/gems/gitlab-linguist-3.0.1/lib/linguist/blob_helper.rb:286:in `language'
	from /home/gitlab-runner/tmp/builds/project-1/app/views/projects/blob/edit.html.haml:31:in `_app_views_projects_blob_edit_html_haml___4486078298386714428_70360759458700'
```

`linguist/blob_helper.rb` defines `Linguist::BlobHelper`, which is included in `Gitlab::Git::Blob` and whose `language` method uses the `mode` method, which this PR modified. Linguist requires it to return nil or a string, but with this PR it returns an int, causing `language`, which is used from GitLab CE, to fail. So what needs to be fixed is that `mode` should return a string, not an int.

**Comment by Soullivaneuh** [comment]
I'm sorry but I'm not responsible of what the mode returns. And it returns an int (octal) that sounds correct for me.

Btw, before this PR, blob mode returns simply nothing because the needed key doesn't exists.

My fix is quite simple: Just changed the blob_entry key to get the existing one: https://github.com/gitlabhq/gitlab_git/pull/50/files#diff-08d64f4982096ddfeefffdd0a2fa2857L29

**Comment by DouweM** [comment]
In any case, I've fixed the issue here in https://gitlab.com/gitlab-org/gitlab_git/merge_requests/19 and I've released version 7.1.6.

**Comment by Soullivaneuh** [comment]
@DouweM not sure if converting value to string is the best practice.

Why not doing int comparison on gitlab linguist instead?

`mode == 0100644` for example (octal) works well and seems proper isn't it?

**Comment by DouweM** [comment]
gitlab-linguist is GitHub's linguist with a couple of GitLab-specific tweaks, but we try to not to change its core too much so that we'll be able to merge new versions back in. I think octal makes just a much sense, but we've got to adapt to their rules in this case. Note that Diff already has modes as strings as well.

**Comment by Razer6** [comment]
@DouweM Gitlab-linguist was AFAIK just to get rid of the python dependency. Current upstream linguist version does not have this dependency anymore so I think it would be a good idea to switch back to the original project.

**Comment by DouweM** [comment]
@Razer6 In that case this is even more of a non-issue; if we're going back on the mainline linguist, we won't have a choice but to use a string mode anyway. Do you want to investigate if we can switch from gitlab-linguist to linguist without issues?

**Comment by randx** [comment]
>  if we can switch from gitlab-linguist to linguist without issues?

@DouweM We can not because it uses latest rugged version :( See https://dev.gitlab.org/gitlab/gitlabhq/issues/2052

**Pull request merged**
